export type GameStyleCase = {
  id: string;
  style: string;
  styleZh: string;
  title: string;
  titleZh: string;
  description: string;
  descriptionZh: string;
  prompt: string;
  before: string;
  after: string;
  alt: string;
};

const asset = (group: string, index: number) => ({
  before: `/examples/generated/${group}-${index}-before.jpg`,
  after: `/examples/generated/${group}-${index}-after.jpg`,
});

/**
 * Original game-character reference frames. These show the kind of style and
 * material direction a prompt can request; they are not NVIDIA DLSS 5 captures.
 */
export const GAME_STYLE_CASES: GameStyleCase[] = [
  { id: 'cyber-courier', style: 'Cyberpunk', styleZh: '赛博朋克', title: 'Neon courier', titleZh: '霓虹快递员', description: 'Keep the courier silhouette and backpack while pushing wet-surface reflections and neon contrast.', descriptionZh: '保留快递员轮廓和背包，强化湿地反光与霓虹对比。', prompt: 'Original game character, preserve silhouette and costume; cyberpunk cinematic lighting, wet pavement, neon reflections, no text.', ...asset('game-cyber', 1), alt: 'Cyberpunk game character before and after a style reference pass' },
  { id: 'forest-ranger', style: 'Fantasy', styleZh: '奇幻', title: 'Misty forest ranger', titleZh: '雾林游侠', description: 'A grounded fantasy look with readable cloth, leather and a stable three-quarter pose.', descriptionZh: '偏写实的奇幻风格，保持布料、皮革和三分之四姿态清晰。', prompt: 'Original fantasy ranger, preserve pose and clothing; misty forest, grounded materials, cinematic game render.', ...asset('game-cyber', 2), alt: 'Fantasy ranger game character before and after a style reference pass' },
  { id: 'tactical-pilot', style: 'Sci-fi', styleZh: '科幻', title: 'Tactical pilot', titleZh: '战术飞行员', description: 'Use hard-surface armor and hangar lighting to check whether a style change keeps mechanical edges consistent.', descriptionZh: '用硬表面护甲与机库光线检查风格变化是否保持机械边缘一致。', prompt: 'Original tactical pilot, preserve armor silhouette and stance; futuristic hangar, realistic materials, no interface text.', ...asset('game-cyber', 3), alt: 'Tactical pilot game character before and after a style reference pass' },
  { id: 'library-mage', style: 'Fantasy', styleZh: '奇幻', title: 'Arcane library mage', titleZh: '魔法图书馆法师', description: 'A character-first style test with warm volumetric light and controlled glowing effects.', descriptionZh: '以角色为中心的风格测试，加入暖色体积光和克制的发光效果。', prompt: 'Original young mage, preserve face and pose; ancient library, warm volumetric light, restrained magical glow.', ...asset('game-cyber', 4), alt: 'Fantasy mage game character before and after a style reference pass' },
  { id: 'desert-mechanic', style: 'Sci-fi', styleZh: '科幻', title: 'Desert mechanic', titleZh: '沙漠机械师', description: 'Keep tools and vehicle proportions fixed while changing the scene toward a dusty sci-fi palette.', descriptionZh: '固定工具和车辆比例，把场景转为尘土感科幻色调。', prompt: 'Original desert mechanic, preserve tools and vehicle proportions; orange dust, cinematic sci-fi game render.', ...asset('game-sci-fi', 1), alt: 'Desert mechanic game character before and after a style reference pass' },
  { id: 'ice-sorcerer', style: 'Fantasy', styleZh: '奇幻', title: 'Ice cathedral sorcerer', titleZh: '冰晶大教堂术士', description: 'Check skin, fur and crystalline materials separately when moving to an ice-fantasy direction.', descriptionZh: '转向冰霜奇幻风格时，分别检查皮肤、毛发和水晶材质。', prompt: 'Original ice sorcerer, preserve face and costume; frozen cathedral, crystalline materials, cool cinematic light.', ...asset('game-sci-fi', 2), alt: 'Ice sorcerer game character before and after a style reference pass' },
  { id: 'dance-android', style: 'Neon anime', styleZh: '霓虹动漫', title: 'Street-dance android', titleZh: '街舞仿生人', description: 'A stylized conversion that should preserve the dance pose while changing color, costume sheen and ambience.', descriptionZh: '在保持舞姿的前提下，改变色彩、服装光泽和环境氛围。', prompt: 'Original android dancer, preserve pose and face; neon anime game style, holographic lighting, no logos.', ...asset('game-sci-fi', 3), alt: 'Android game character before and after a style reference pass' },
  { id: 'forest-guardian', style: 'Bioluminescent fantasy', styleZh: '生物荧光奇幻', title: 'Forest guardian', titleZh: '森林守护者', description: 'Use leaves, antlers and bioluminescent accents as a material-consistency test.', descriptionZh: '用叶片、鹿角和生物荧光点作为材质一致性测试。', prompt: 'Original forest guardian, preserve silhouette and staff; bioluminescent plants, grounded fantasy game render.', ...asset('game-sci-fi', 4), alt: 'Forest guardian game character before and after a style reference pass' },
  { id: 'moonlit-knight', style: 'Dark fantasy', styleZh: '暗黑奇幻', title: 'Moonlit knight', titleZh: '月下骑士', description: 'A reflective armor and wet-stone case for checking specular highlights and silhouette stability.', descriptionZh: '通过反光铠甲和湿石地面检查高光与轮廓稳定性。', prompt: 'Original armored knight, preserve armor silhouette and sword; moonlit bridge, dark fantasy, controlled reflections.', ...asset('game-fantasy', 1), alt: 'Moonlit knight game character before and after a style reference pass' },
  { id: 'sky-pirate', style: 'Adventure', styleZh: '冒险', title: 'Sky pirate captain', titleZh: '天空海盗船长', description: 'Keep the captain pose and coat while converting the backdrop to a bright floating-island adventure.', descriptionZh: '保留船长姿势和外套，将背景转为明亮的浮空岛冒险场景。', prompt: 'Original sky pirate captain, preserve pose and coat; floating islands, bright adventure game lighting, no logos.', ...asset('game-fantasy', 2), alt: 'Sky pirate game character before and after a style reference pass' },
  { id: 'bamboo-archer', style: 'Stealth action', styleZh: '潜行动作', title: 'Bamboo courtyard archer', titleZh: '竹院潜行弓手', description: 'A low-light case where the bow, hands and layered clothing need to remain legible.', descriptionZh: '低光环境下检查弓、手部和层叠服装是否依然清晰。', prompt: 'Original stealth archer, preserve bow, hands and clothing; bamboo courtyard at dusk, cinematic action game render.', ...asset('game-fantasy', 3), alt: 'Stealth archer game character before and after a style reference pass' },
  { id: 'volcanic-warrior', style: 'Elemental fantasy', styleZh: '元素奇幻', title: 'Volcanic warrior', titleZh: '火山战士', description: 'Check ember glow, armor edges and skin tone separately so the style pass does not flatten detail.', descriptionZh: '分别检查火星光、铠甲边缘和肤色，避免风格转换抹平细节。', prompt: 'Original volcanic warrior, preserve armor and stance; ember-lit volcanic arena, elemental fantasy game render.', ...asset('game-fantasy', 4), alt: 'Volcanic warrior game character before and after a style reference pass' },
  { id: 'firefighter', style: 'Realistic action', styleZh: '写实动作', title: 'Urban rescue firefighter', titleZh: '城市救援消防员', description: 'A realistic conversion target for smoke, reflective safety fabric and a readable face.', descriptionZh: '适合检查烟雾、反光安全面料和人物面部的写实转换。', prompt: 'Original firefighter character, preserve helmet, face and safety stripes; smoky city rescue scene, realistic game render.', ...asset('game-modern', 1), alt: 'Firefighter game character before and after a style reference pass' },
  { id: 'mars-astronaut', style: 'Hard sci-fi', styleZh: '硬科幻', title: 'Mars rover astronaut', titleZh: '火星探测宇航员', description: 'Use the suit seams, rover geometry and red-rock lighting to audit a hard-surface style conversion.', descriptionZh: '用宇航服接缝、探测车几何和红岩光线审查硬表面风格转换。', prompt: 'Original astronaut, preserve suit seams and rover proportions; red planet, hard sci-fi game lighting.', ...asset('game-modern', 2), alt: 'Astronaut game character before and after a style reference pass' },
  { id: 'esports-player', style: 'Modern cinematic', styleZh: '现代电影感', title: 'Esports player portrait', titleZh: '电竞选手肖像', description: 'Keep the face and headset shape stable while shifting the scene to a cinematic arena palette.', descriptionZh: '保持面部和耳机形状稳定，将场景转为电影感竞技场色调。', prompt: 'Original esports player, preserve face and headset; dramatic arena lighting, modern cinematic game portrait.', ...asset('game-modern', 3), alt: 'Esports player game character before and after a style reference pass' },
  { id: 'noir-detective', style: 'Noir', styleZh: '黑色电影', title: 'Rainy noir detective', titleZh: '雨夜黑色侦探', description: 'A coat, hat and wet-alley conversion where reflections and facial identity should stay anchored.', descriptionZh: '在风衣、礼帽和湿巷场景中保持反光与身份锚定。', prompt: 'Original detective character, preserve hat, coat and face; rainy noir alley, cinematic game lighting, no readable signs.', ...asset('game-modern', 4), alt: 'Noir detective game character before and after a style reference pass' },
  { id: 'anime-swordswoman', style: 'Anime action', styleZh: '动漫动作', title: 'Wind-swept swordswoman', titleZh: '风中女剑士', description: 'An anime-style reference for hair strands, cloth motion and a stable sword silhouette.', descriptionZh: '动漫风格下检查发丝、衣料运动和剑的轮廓稳定性。', prompt: 'Original anime game swordswoman, preserve sword and pose; wind-swept cliff, expressive eyes, grounded light.', ...asset('game-anime', 1), alt: 'Anime swordswoman game character before and after a style reference pass' },
  { id: 'robot-companion', style: 'Warm sci-fi', styleZh: '温暖科幻', title: 'Greenhouse robot companion', titleZh: '温室机器人伙伴', description: 'Check friendly face lights, white panels and plant edges in a softer game-art direction.', descriptionZh: '在柔和游戏美术风格中检查表情灯、白色面板和植物边缘。', prompt: 'Original small robot companion, preserve panel shapes and face lights; sunlit greenhouse, warm sci-fi game art.', ...asset('game-anime', 2), alt: 'Robot companion game character before and after a style reference pass' },
  { id: 'masked-vigilante', style: 'Anime noir', styleZh: '动漫黑色电影', title: 'Rooftop masked vigilante', titleZh: '屋顶蒙面守望者', description: 'A dark silhouette and sunset rim-light case for checking mask edges and cape folds.', descriptionZh: '用深色轮廓和日落轮廓光检查面罩边缘与披风褶皱。', prompt: 'Original masked vigilante, preserve mask and cape silhouette; rooftop sunset, anime noir game render.', ...asset('game-anime', 3), alt: 'Masked vigilante game character before and after a style reference pass' },
  { id: 'underwater-explorer', style: 'Aquatic sci-fi', styleZh: '水下科幻', title: 'Underwater explorer', titleZh: '水下探索者', description: 'Use glass, water caustics and a readable helmet to check a cool aquatic style conversion.', descriptionZh: '用玻璃、水面焦散和清晰头盔检查冷色水下风格转换。', prompt: 'Original ocean explorer, preserve helmet and suit; luminous underwater station, aquatic sci-fi game render.', ...asset('game-anime', 4), alt: 'Underwater explorer game character before and after a style reference pass' },
];
