/**
 * DLSS5 Studio 落地页文案（英文 / 简体中文）—— 纯数据，无逻辑、无依赖、无组件。
 *
 * 单一来源：alibaba-drive/DLSS5-Studio/landing/index.html（2026-09-26 定稿）。
 * 改文案要在两边一起改：先改 HTML，再重跑抽取脚本
 *   ~/opt/anaconda3/bin/python <scratchpad>/extract-studio-copy.py
 * 这份文件是生成物，请勿手改。
 *
 * 键名就是 HTML 上 data-i18n / data-i18n-alt / data-i18n-aria 的值，
 * 外加 meta.title / meta.desc（<title> 与 meta description）。
 * 值里的 HTML 实体已解码；连续空白已压成一个空格并去掉首尾。
 * STUDIO_HTML_KEYS 里的键（源自 data-i18n-html）保留 <code> <em> <strong> 这类行内标记，
 * 页面用 dangerouslySetInnerHTML 渲染；其余键一律是纯文本。
 */

export const STUDIO_COPY = {
  'en-US': {
    'meta.title': 'DLSS5 Studio — “DLSS download” explained, and a local DLSS 5 neural rendering tool',
    'meta.desc': 'Looking for a DLSS download? NVIDIA’s DLSS has no standalone installer — it ships inside games. DLSS5 Studio is an independent local GUI for NVIDIA’s Visual Enhancer DLSS 5 neural rendering pipeline: batch images and video, wipe compare, difference view and a Live enhanced preview.',
    'nav.which': 'Which DLSS?',
    'nav.features': 'Features',
    'nav.live': 'Live',
    'nav.shots': 'Screenshots',
    'nav.download': 'Download',
    'nav.faq': 'FAQ',
    'nav.lang': 'Language',
    'nav.theme': 'Switch theme',
    'hero.eyebrow': 'Independent third-party project · not affiliated with NVIDIA',
    'hero.h1': 'A local desktop front-end for NVIDIA’s <em class="hl">DLSS\u00a05</em> neural rendering pipeline',
    'hero.sub': 'DLSS5 Studio replaces the stock Qt interface of the Visual Enhancer release with a local web UI: asset rail on the left, wipe-compare canvas in the middle, parameter inspector on the right, batch queue along the bottom. Everything runs on your own machine.',
    'hero.ctaPrimary': 'Download the portable build',
    'hero.ctaSecondary': 'See what it does',
    'hero.meta.os': 'Windows 10 / 11 · x64',
    'hero.meta.gpu': 'NVIDIA RTX GPU',
    'hero.meta.install': 'No installer, no Python, no account',
    'hero.shot.alt': 'The DLSS5 Studio window: an asset rail on the left, a wipe-compare canvas in the middle showing a render 4× larger than the source, a parameter inspector on the right, and a job queue along the bottom.',
    'hero.shot.cap': 'The real application: 1024×1024 source on the left of the wipe, the finished 4× render on the right.',
    'which.eyebrow': 'First things first',
    'which.title': 'Which “DLSS download” are you looking for?',
    'which.sub': 'Two different things are called DLSS here. Picking the right one first saves a wasted download.',
    'which.official.tag': 'NVIDIA official',
    'which.official.title': 'NVIDIA’s DLSS — Super Resolution, Frame Generation, Ray Reconstruction',
    'which.official.body': 'There is no standalone DLSS download. DLSS ships inside games as <code>nvngx_dlss.dll</code> and arrives with the game or its updater. For the official technology overview, drivers and the NVIDIA App, go to NVIDIA’s own site.',
    'which.official.cta': 'Open nvidia.com',
    'which.mine.tag': 'This page',
    'which.mine.title': 'DLSS5 Studio — the tool on this page',
    'which.mine.body': 'A local GUI for NVIDIA’s Visual Enhancer neural-rendering pipeline: the DLSS 5 stage inside it, plus RTX Super Resolution, denoising, sharpening and frame interpolation. Batch-process your own images and videos, entirely offline, with nothing uploaded anywhere.',
    'which.mine.cta': 'Go to the download',
    'feat.eyebrow': 'What it does',
    'feat.title': 'The whole pipeline, rebuilt for batch work',
    'feat.sub': 'The processing layer is untouched: same engine, same parameters, same preset format. Only “who drives it, and with what interface” changed.',
    'feat.1.t': 'DLSS 5 neural rendering',
    'feat.1.d': 'The one stage in the pipeline with no substitute. Whether it is on is stated in three permanent places — the nav badge, the canvas label and the inspector group header — so it can never be silently dropped.',
    'feat.2.t': 'RTX Super Resolution',
    'feat.2.d': 'VSR quality 1–4, scale factor and target size, with the DLAA / Quality / Balanced / Performance / Ultra Performance steps. There is no 4× step — 4× means Lanczos 2× into DLSS Performance.',
    'feat.3.t': 'Video and frame interpolation',
    'feat.3.d': 'Videos go through neural rendering, RTX Super Resolution and interpolation to 60 fps, encoded with H.265 NVENC into MKV at the original frame rate. Without NVENC it falls back to a software encoder and says so in the job log.',
    'feat.4.t': 'Batch queue',
    'feat.4.d': 'Serial execution with live progress, cancel and retry. Output names are predictable (<code>&lt;name&gt;_&lt;preset label&gt;</code>), a collision becomes <code> (2)</code>, and an existing file is never overwritten.',
    'feat.5.t': 'Wipe compare and difference view',
    'feat.5.d': 'Drag the centre line to wipe between source and result. Videos play in place with frame stepping and live A/B switching. The Difference view subtracts pixel by pixel — brighter means a bigger change — at 1× / 3× / 8× gain.',
    'feat.6.t': 'Live enhanced preview',
    'feat.6.d': 'Runs NVIDIA’s own Live pipeline and publishes the enhanced picture to the panel over HLS, with neural-rendering parameters hot-updating mid-playback. It is an enhanced preview, not real-time video — see the numbers below.',
    'feat.7.t': 'Eight interface languages',
    'feat.7.d': 'English, Simplified Chinese, Japanese, Korean, Russian, Ukrainian, Indonesian and Estonian — the same set and the same detection order as dlss5nvidia.com. Adding <code>?lang=ja</code> to the address pins one language for one person.',
    'feat.8.t': 'Two-way preset compatibility',
    'feat.8.d': 'What Studio saves is the official <code>dlss5-visual-enhancer-settings-preset</code> v18 document — drag it straight into the original application, and vice versa. Controls bind to the engine’s own <code>UISettings</code> field names, with no renaming layer in between.',
    'live.eyebrow': 'Live',
    'live.title': 'Watch it work, one frame at a time',
    'live.sub': 'Live runs NVIDIA’s Live pipeline in a separate worker process and publishes the enhanced picture as HLS. It is an <strong>enhanced preview</strong>, not real-time video: every frame pays the full neural-rendering cost.',
    'live.table.cap': 'Measured on an RTX 4090 (driver 591.86), 1080p source, default preset.',
    'live.th.cap': 'Resolution cap',
    'live.th.frame': 'Neural render / frame',
    'live.th.fps': 'Measured throughput',
    'live.th.buffer': 'Buffer',
    'live.ok': 'keeps up',
    'live.bad': 'falls behind — will stutter',
    'live.row.scale': '720p · preview scale 50%',
    'live.note.lead': 'It is an enhanced preview, not real-time video.',
    'live.note.body': 'Time to first frame is 6–7 seconds (engine cold start). End-to-end latency is about 8 seconds at the default 6 s + 2 s buffering, and can be pulled down to 3–4 seconds with 1 s segments and a 3 s buffer. Dropping the resolution cap one step, or setting the preview scale to 50%, buys a lot of smoothness.',
    'live.note.badge': 'The panel carries a permanent “Preview · not real-time” chip, and shows measured fps, per-frame cost, buffer state, dropped samples and enhanced frame count while it runs.',
    'live.fact.input': 'Input sources match the original: local video files, direct streams (http, https, rtmp, rtmps, rtsp, srt) and YouTube / Twitch pages.',
    'live.fact.screen': '<strong>Screen capture is not supported</strong> — NVIDIA’s source resolver has no such path, and a browser cannot add one.',
    'live.fact.hls': 'The HLS address is bound to loopback only and can be copied into mpv or VLC.',
    'live.shot.alt': 'The Live panel running: source picker, resolution cap, preview scale, segment length and buffer controls on the left; the playing enhanced picture on the right; and a status block reading measured fps 9.1, target fps 10.00, buffer 5.4 s, 95 enhanced frames and 132 dropped samples, followed by the HLS address.',
    'live.shot.cap': 'A running session: 9.1 fps measured against a 10 fps target, 5.4 s of buffer, 95 frames enhanced — and the HLS address to hand to mpv or VLC.',
    'shots.eyebrow': 'Screenshots',
    'shots.title': 'The actual interface',
    'shots.sub': 'Straight captures of the running application. Nothing here is mocked up.',
    'shots.video.alt': 'A video job open for comparison: a 320×240 source playing, the 640×480 output on the right of the wipe, and transport controls with frame stepping underneath.',
    'shots.video.cap': 'Video compare: play the result in place, step frame by frame, switch source / compare / result live.',
    'shots.diff.alt': 'The difference view: the pixel-by-pixel difference between source and result, rendered dark with fine concentric noise structure, with a magnifier open and a 1× / 3× / 8× gain selector in the toolbar.',
    'shots.diff.cap': 'Difference view: a pixel-by-pixel subtraction of source and result — brighter means a bigger change.',
    'shots.keys.alt': 'The keyboard shortcut dialog, listing shortcuts for the asset rail, the queue, parameters and presets, and canvas comparison.',
    'shots.keys.cap': 'A keyboard path for nearly everything — Ctrl+O, Ctrl+A, Enter to process, F to fit, Z for the magnifier, Space to play.',
    'req.eyebrow': 'Requirements',
    'req.title': 'What you need',
    'req.sub': 'A modern Windows machine with an RTX card, and a browser you already have.',
    'req.os.t': 'Operating system',
    'req.os.d': 'Windows 10 (1909 or newer, 64-bit) or Windows 11',
    'req.gpu.t': 'GPU',
    'req.gpu.d': 'An NVIDIA RTX GPU — RTX 20 series or newer',
    'req.driver.t': 'Driver',
    'req.driver.d': '610 or newer for hardware NVENC encoding. On an older driver the encoder falls back to a software codec automatically and says so in the job message.',
    'req.ram.t': 'Memory',
    'req.ram.d': '8 GB minimum; 16 GB recommended for 1080p and 4K video',
    'req.disk.t': 'Disk',
    'req.disk.d': 'About 3 GB free — the portable folder is roughly 1.1 GB unpacked',
    'req.browser.t': 'Browser',
    'req.browser.d': 'Any recent Edge or Chrome. The interface is served from loopback; nothing is fetched from the internet.',
    'req.engine.t': 'Engine',
    'req.engine.d': 'The NVIDIA Visual Enhancer release package. Studio drives it — it is not bundled inside this download.',
    'dl.eyebrow': 'Download',
    'dl.title': 'Portable — unzip and run',
    'dl.sub': 'Nothing to install: no Python, no Node, no service, no registry entries. Double-click the launcher and the window opens; deleting the folder is the uninstall.',
    'dl.cta': 'Download the portable ZIP',
    'dl.ctaPending': 'Get DLSS5 Studio — see the distribution status',
    'dl.size': 'Windows x64 · portable ZIP · no installer · about 512 MB',
    'dl.f1': 'Double-click this one to start the app',
    'dl.f2': 'Self-check: GPU, driver, dependencies, one real render end to end',
    'dl.f3': 'Optional: copy to C:\\DLSS5Studio and make a desktop shortcut',
    'dl.f4': 'The full notes, including the NVIDIA notice',
    'dl.f5': 'The NVIDIA Visual Enhancer release package, unmodified',
    'dl.f6': 'The headless bridge Studio uses to call the engine',
    'dl.f7': 'The new interface: launcher, backend and built front end',
    'dl.status.title': 'Distribution status',
    'dl.status.body': 'Studio itself is a shell; the engine it drives is NVIDIA’s Visual Enhancer release, redistributed byte-for-byte unchanged. Before public distribution, the DLSS components must be packaged under the NVIDIA RTX SDKs licence programming guide §4.2 with NVIDIA notified first, and three libraries that are not part of the public SDK need explicit NVIDIA authorisation — along with confirmation that shipping them is permitted at all:',
    'dl.status.nr': '(feature 18, the DLSS 5 neural rendering stage)',
    'dl.status.body2': 'NVIDIA’s original signatures on these libraries must be preserved — re-signing them is not allowed. Until that authorisation lands, the build is distributed internally only, and the button above says so instead of handing out a link.',
    'faq.eyebrow': 'FAQ',
    'faq.title': 'Questions people actually ask',
    'faq.q1': 'So where do I download DLSS?',
    'faq.a1': 'Nowhere — and that is not a dodge. DLSS is not a program you install; it is a library compiled into a game, shipped as <code>nvngx_dlss.dll</code> and updated either by the game itself or by swapping that DLL. A “DLSS download” page that hands you an installer is selling you something else. What is downloadable on this page is DLSS5 Studio, the local GUI described above.',
    'faq.q2': 'Is this an NVIDIA product?',
    'faq.a2': 'No. It is an independent third-party project, not affiliated with, endorsed by or sponsored by NVIDIA. “DLSS”, “RTX”, “GeForce” and “NVIDIA” are trademarks of NVIDIA Corporation, used here only to describe what the engine does. The application never pretends to be DLSS when DLSS is not running.',
    'faq.q3': 'Are my files uploaded anywhere?',
    'faq.a3': 'No. There is no account, no telemetry and no cloud step — everything runs on your GPU, on your machine. The background service listens on 127.0.0.1 only and rejects any non-loopback host or origin, so a web page you happen to have open cannot reach it either.',
    'faq.q4': 'Does it modify the engine?',
    'faq.a4': 'No. The engine is called exactly the way the release package is meant to be called, using the package’s own bundled interpreter. Studio changes who calls it and what interface does the calling — nothing inside the engine is patched.',
    'faq.q5': 'Will my presets still work in the original app?',
    'faq.a5': 'Yes, in both directions. A preset saved by Studio is the official <code>dlss5-visual-enhancer-settings-preset</code> v18 document, byte for byte — drag it into the original application and it loads. The reverse works too.',
    'faq.q6': 'Can it enhance my game in real time, or capture my screen?',
    'faq.a6': 'No. Screen capture does not exist in NVIDIA’s pipeline at all, and Live is an enhanced preview running at a few frames per second — not an overlay that can sit on top of a game. A 1080p source measures about 2.4 fps on the reference machine.',
    'faq.q7': 'What happens without the Visual Enhancer release package?',
    'faq.a7': 'Studio starts on a demo engine: it does lossless scaling, denoising and sharpening, and labels the window “demo engine — not DLSS output” the entire time. Nothing pretends to be DLSS, and Live stays disabled with the reason attached.',
    'faq.q8': 'Is it free? Does it phone home?',
    'faq.a8': 'There is no account, licence key or payment step, and no network call of any kind. All runtime data — the asset index, thumbnails, preview cache, outputs and your presets — lives in one <code>studio/data/</code> folder you can delete at any time.',
    'foot.legal': 'Independent third-party project. Not affiliated with, endorsed by or sponsored by NVIDIA Corporation. DLSS, RTX, GeForce and NVIDIA are trademarks of NVIDIA Corporation, used here only to describe the technology this tool drives.',
    'foot.engine': 'Built on the NVIDIA Visual Enhancer release package, redistributed unmodified. All screenshots show the real application.',
    'foot.year': 'DLSS5 Studio · 2026',
  },
  'zh-CN': {
    'meta.title': 'DLSS5 Studio — 「DLSS 下载」到底该下什么，以及一套本地 DLSS 5 神经渲染工具',
    'meta.desc': '在找 DLSS 下载？NVIDIA 的 DLSS 没有独立安装包，它随游戏以 nvngx_dlss.dll 分发。DLSS5 Studio 是 NVIDIA Visual Enhancer（含 DLSS 5 神经渲染）的一套独立、纯本地的图形界面：批量处理图片与视频、擦除对比、差值视图、Live 增强预览。',
    'nav.which': '哪个 DLSS',
    'nav.features': '功能',
    'nav.live': 'Live',
    'nav.shots': '界面截图',
    'nav.download': '下载',
    'nav.faq': '常见问题',
    'nav.lang': '语言',
    'nav.theme': '切换主题',
    'hero.eyebrow': '独立第三方项目 · 与 NVIDIA 无隶属关系',
    'hero.h1': '给 NVIDIA <em class="hl">DLSS\u00a05</em> 神经渲染管线，一套跑在本机上的桌面界面',
    'hero.sub': 'DLSS5 Studio 把 Visual Enhancer 官方发布包那套 Qt 界面换成了本地网页界面：左边素材栏、中间擦除对比画布、右边参数检查器、底部处理队列。全部算力都在你自己的机器上。',
    'hero.ctaPrimary': '下载免安装版',
    'hero.ctaSecondary': '看看它能做什么',
    'hero.meta.os': 'Windows 10 / 11 · x64',
    'hero.meta.gpu': 'NVIDIA RTX 显卡',
    'hero.meta.install': '免安装、不用 Python、不用账号',
    'hero.shot.alt': 'DLSS5 Studio 的运行界面：左侧素材栏；中间是擦除对比画布，右半边是放大 4 倍后的渲染结果；右侧参数检查器；底部处理队列。',
    'hero.shot.cap': '真实运行的界面：擦除线左边是 1024×1024 原图，右边是 4 倍渲染结果。',
    'which.eyebrow': '先说清楚',
    'which.title': '你要找的「DLSS 下载」是哪一个？',
    'which.sub': '这一页上有两个东西都叫 DLSS。先分清是哪个，能省掉一次白下。',
    'which.official.tag': 'NVIDIA 官方',
    'which.official.title': 'NVIDIA 的 DLSS —— 超分辨率、帧生成、光线重建',
    'which.official.body': 'DLSS 没有独立安装包。它是编译进游戏里的库 <code>nvngx_dlss.dll</code>，随游戏本体或游戏更新器一起到达。想看官方技术说明、下载驱动和 NVIDIA App，请去 NVIDIA 官网。',
    'which.official.cta': '前往 nvidia.com',
    'which.mine.tag': '本页工具',
    'which.mine.title': 'DLSS5 Studio —— 这一页介绍的工具',
    'which.mine.body': 'NVIDIA Visual Enhancer 神经渲染管线的一套本地图形界面：里面的 DLSS 5 阶段，加上 RTX 超分、降噪、锐化和帧插值。对自己的图片和视频批量处理，全程离线，什么都不上传。',
    'which.mine.cta': '去下载',
    'feat.eyebrow': '功能',
    'feat.title': '整条管线都在，为批量作业重新做了一遍',
    'feat.sub': '处理层一行未改：同一个引擎、同一套参数、同一种预设格式。变的只是「谁来调它、用什么界面调」。',
    'feat.1.t': 'DLSS 5 神经渲染',
    'feat.1.d': '整条管线里唯一没有替代品的步骤。开没开，界面上有三处常驻显示 —— 顶栏徽标、画布标签、检查器分组标题，不会在不知情的时候把它跑丢。',
    'feat.2.t': 'RTX 超分',
    'feat.2.d': 'VSR 质量 1–4 档、倍率与目标尺寸，配合 DLAA / Quality / Balanced / Performance / Ultra Performance 五档 DLSS 档位。没有 4× 这一档 —— 想要 4× 就是先 Lanczos 2×、再让 DLSS 走 Performance。',
    'feat.3.t': '视频与帧插值',
    'feat.3.d': '视频走神经渲染 + RTX 超分 + 补帧到 60fps，用 H.265 NVENC 编成 MKV 并保留原帧率。没有 NVENC 时自动换同族软件编码器，并在作业消息里如实说明。',
    'feat.4.t': '批量队列',
    'feat.4.d': '串行执行，实时进度、取消、重试。输出命名可预测（<code>&lt;原文件名&gt;_&lt;预设标签&gt;</code>），重名变成 <code> (2)</code>，已存在的文件绝不覆盖。',
    'feat.5.t': '擦除对比与差值视图',
    'feat.5.d': '拖中间白线擦除对比；视频可以原地播放、逐帧、实时 A/B 切换。差值档逐像素相减 —— 越亮改动越大 —— 增益 1× / 3× / 8×。',
    'feat.6.t': 'Live 增强预览',
    'feat.6.d': '把 NVIDIA 官方 Live 管线跑起来，增强后的画面用 HLS 推给面板，神经渲染参数还能在播放中热更新。它是增强预览，不是实时视频 —— 数字见下一节。',
    'feat.7.t': '八种界面语言',
    'feat.7.d': 'English、简体中文、日本語、한국어、Русский、Українська、Bahasa Indonesia、Eesti —— 与 dlss5nvidia.com 同一套语种、同一套检测顺序。在地址后面加 <code>?lang=ja</code> 可以给某个人固定语言。',
    'feat.8.t': '预设双向兼容',
    'feat.8.d': 'Studio 存出的就是官方 <code>dlss5-visual-enhancer-settings-preset</code> v18 文档 —— 可以直接拖进原版应用，反过来也一样。控件直接绑引擎自己的 <code>UISettings</code> 字段名，中间没有改名层。',
    'live.eyebrow': 'Live',
    'live.title': '边算边看，一帧一帧地看',
    'live.sub': 'Live 把 NVIDIA 官方 Live 管线跑在独立的工作进程里，把增强后的画面以 HLS 推出来。它是<strong>增强预览</strong>，不是实时视频：每一帧都要付全额神经渲染的代价。',
    'live.table.cap': '实测环境：RTX 4090（驱动 591.86），1080p 输入，默认预设。',
    'live.th.cap': '分辨率上限',
    'live.th.frame': '每帧神经渲染',
    'live.th.fps': '实测吞吐',
    'live.th.buffer': '缓冲',
    'live.ok': '达标',
    'live.bad': '追不上，会卡',
    'live.row.scale': '720p · 预览尺度 50%',
    'live.note.lead': '它是增强预览，不是实时视频。',
    'live.note.body': '首帧要等 6–7 秒（引擎冷启动）。端到端延迟默认约 8 秒（分段 6 秒 + 缓冲 2 秒），把分段调到 1 秒、缓冲调到 3 秒可以降到 3–4 秒。分辨率上限降一档，或把预览尺度调到 50%，流畅度会明显好转。',
    'live.note.badge': '面板上常驻一枚「预览 · 非实时」徽标，并在运行中显示实测帧率、每帧耗时、缓冲状态、丢弃采样和已增强帧数。',
    'live.fact.input': '输入源与原版一致：本地视频文件、直链流（http、https、rtmp、rtmps、rtsp、srt）、YouTube / Twitch 页面。',
    'live.fact.screen': '<strong>不做屏幕采集</strong> —— 官方管线里根本没有这条路径，浏览器也补不出来。',
    'live.fact.hls': 'HLS 地址只绑回环，可以复制给 mpv / VLC 直接看。',
    'live.shot.alt': '正在运行的 Live 面板：左侧是输入源、分辨率上限、预览尺度、分段与缓冲控件；右侧是正在播放的增强画面；下方状态区显示实测帧率 9.1、目标帧率 10.00、缓冲 5.4 秒、已增强 95 帧、采样丢弃 132，末尾是 HLS 地址。',
    'live.shot.cap': '一次真实会话：目标 10 fps，实测 9.1 fps，缓冲 5.4 秒，已增强 95 帧 —— 以及可以交给 mpv / VLC 的 HLS 地址。',
    'shots.eyebrow': '界面截图',
    'shots.title': '真实的界面',
    'shots.sub': '全部是运行中程序的原样截图，没有一张是效果图。',
    'shots.video.alt': '一个视频作业的对比：320×240 原片在播放，擦除线右侧是 640×480 的输出，下方是带逐帧按钮的播放控制条。',
    'shots.video.cap': '视频对比：原地播放结果、逐帧步进、原片 / 对比 / 结果三档实时切换。',
    'shots.diff.alt': '差值视图：原图与结果逐像素相减后的画面，整体偏暗、可见细密的同心噪点结构，同时开着放大镜，工具条上有 1× / 3× / 8× 增益选择。',
    'shots.diff.cap': '差值视图：原图与结果逐像素相减 —— 越亮改动越大。',
    'shots.keys.alt': '快捷键面板，列出素材栏、队列、参数与预设、画布对比四组快捷键。',
    'shots.keys.cap': '几乎每一步都有键盘路径 —— Ctrl+O 加文件、Ctrl+A 全选、Enter 处理、F 适应、Z 放大镜、空格播放。',
    'req.eyebrow': '系统要求',
    'req.title': '你需要什么',
    'req.sub': '一台带 RTX 显卡的现代 Windows 机器，以及一个你本来就有浏览器。',
    'req.os.t': '操作系统',
    'req.os.d': 'Windows 10（1909 及以上，64 位）或 Windows 11',
    'req.gpu.t': '显卡',
    'req.gpu.d': 'NVIDIA RTX 显卡 —— RTX 20 系及以上',
    'req.driver.t': '驱动',
    'req.driver.d': '要用硬件 NVENC 编码需要 610 或更新。驱动更旧时编码器会自动退到软件编码，并在作业消息里说明。',
    'req.ram.t': '内存',
    'req.ram.d': '最低 8 GB；1080p 与 4K 视频建议 16 GB',
    'req.disk.t': '磁盘',
    'req.disk.d': '约 3 GB 可用空间 —— 免安装目录解压后大约 1.1 GB',
    'req.browser.t': '浏览器',
    'req.browser.d': '任意较新的 Edge 或 Chrome。界面从回环地址提供，不从互联网拉任何东西。',
    'req.engine.t': '引擎',
    'req.engine.d': 'NVIDIA Visual Enhancer 官方发布包。Studio 负责调用它 —— 它不在这个下载里。',
    'dl.eyebrow': '下载',
    'dl.title': '免安装 —— 解压就能用',
    'dl.sub': '什么都不用装：不用 Python、不用 Node、不装服务、不写注册表。双击启动脚本就开窗口；删掉文件夹就等于卸载。',
    'dl.cta': '下载免安装包（ZIP）',
    'dl.ctaPending': '获取 DLSS5 Studio —— 先看分发状态',
    'dl.size': 'Windows x64 · 免安装 ZIP · 无安装器 · 约 512 MB',
    'dl.f1': '双击这个启动程序',
    'dl.f2': '自检：显卡、驱动、依赖、真渲染跑一遍',
    'dl.f3': '可选：搬到 C:\\DLSS5Studio 并建桌面快捷方式',
    'dl.f4': '完整说明，含 NVIDIA 声明',
    'dl.f5': 'NVIDIA Visual Enhancer 官方发布包，原样未改动',
    'dl.f6': 'Studio 调引擎用的 headless 桥',
    'dl.f7': '新界面：启动器、后端与构建好的前端',
    'dl.status.title': '分发状态',
    'dl.status.body': 'Studio 本身只是一层壳；它驱动的引擎是 NVIDIA 的 Visual Enhancer 官方发布包，逐字节原样分发。公开发布之前，DLSS 组件必须按 NVIDIA RTX SDKs License 编程指南 §4.2 打包并事先通知 NVIDIA；另外三个不在公开 SDK 内的库需要 NVIDIA 明确授权，同时确认随包分发这些库本身是被允许的：',
    'dl.status.nr': '（feature 18，即 DLSS 5 神经渲染那一步）',
    'dl.status.body2': '这些库上 NVIDIA 的原始签名必须保留 —— 不允许重签。在授权落地之前，这个包只在内部通道分发，所以上面的按钮不给出链接，而是指向这段说明。',
    'faq.eyebrow': '常见问题',
    'faq.title': '真正会被问到的问题',
    'faq.q1': '那 DLSS 到底去哪儿下载？',
    'faq.a1': '哪儿都不用 —— 这不是搪塞。DLSS 不是一个你安装的程序，它是编译进游戏里的库，以 <code>nvngx_dlss.dll</code> 的形式随游戏到达，之后要么由游戏自己更新，要么替换那个 DLL。一个「DLSS 下载」页面如果塞给你一个安装器，那它卖的是别的东西。这一页能下载的是上面介绍的 DLSS5 Studio。',
    'faq.q2': '这是 NVIDIA 的产品吗？',
    'faq.a2': '不是。这是一个独立第三方项目，与 NVIDIA 没有隶属、背书或赞助关系。「DLSS」「RTX」「GeForce」「NVIDIA」是 NVIDIA Corporation 的商标，这里只用来说明这个引擎在做什么。DLSS 没在跑的时候，这个程序绝不会假装自己是 DLSS。',
    'faq.q3': '我的素材会被上传吗？',
    'faq.a3': '不会。没有账号、没有埋点、没有云端环节 —— 全部在你自己的显卡、自己的机器上跑。后台服务只监听 127.0.0.1，并拒绝任何非回环的 Host 与 Origin，所以你随手开着的网页也够不到它。',
    'faq.q4': '它改引擎吗？',
    'faq.a4': '不改。引擎完全按官方发布包既定的方式被调用，用的是发布包自带的解释器。Studio 改的只是「谁来调、用什么界面调」，引擎内部一个字节都没打补丁。',
    'faq.q5': '我的预设还能在原版应用里用吗？',
    'faq.a5': '能，而且是双向的。Studio 存出的预设就是官方 <code>dlss5-visual-enhancer-settings-preset</code> v18 文档，逐字节一致 —— 拖进原版应用就能读。反过来也一样。',
    'faq.q6': '能实时增强我的游戏吗？能采集屏幕吗？',
    'faq.a6': '不能。官方管线里根本没有屏幕采集这条路径，而 Live 是每秒几帧的增强预览，不是能盖在游戏上的叠加层。1080p 输入在参考机器上实测约 2.4 fps。',
    'faq.q7': '没有 Visual Enhancer 官方发布包会怎样？',
    'faq.a7': 'Studio 会用替代引擎启动：做无损放大、降噪和锐化，窗口全程标注「演示引擎（非 DLSS 输出）」。不会有任何东西冒充 DLSS，Live 按钮置灰并把原因挂在提示里。',
    'faq.q8': '免费吗？会联网吗？',
    'faq.a8': '没有账号、没有许可证密钥、没有付款环节，也没有任何网络请求。运行期数据 —— 素材索引、缩略图、预览缓存、输出和你的预设 —— 都在一个 <code>studio/data/</code> 目录里，随时可以删。',
    'foot.legal': '独立第三方项目。与 NVIDIA Corporation 无隶属、背书或赞助关系。DLSS、RTX、GeForce、NVIDIA 是 NVIDIA Corporation 的商标，此处仅用于说明本工具驱动的技术。',
    'foot.engine': '基于 NVIDIA Visual Enhancer 官方发布包构建，原样分发。所有截图均为真实运行界面。',
    'foot.year': 'DLSS5 Studio · 2026',
  },
} as const;

/** 带行内标记、需要用 dangerouslySetInnerHTML 渲染的键。 */
export const STUDIO_HTML_KEYS: string[] = [
  'hero.h1',
  'which.official.body',
  'feat.4.d',
  'feat.7.d',
  'feat.8.d',
  'live.sub',
  'live.fact.screen',
  'faq.a1',
  'faq.a5',
  'faq.a8',
];
